apiVersion: v1
kind: ConfigMap
metadata:
  name: saludo-config
data:
  SPRING_PROFILES_ACTIVE: "cloud"
  SERVICIO: "http://pago:80"
  NEW_RELIC_APP_NAME: "saludo"
  NEW_RELIC_LOG: "stdout"
  JAVA_TOOL_OPTIONS: "-javaagent:/opt/newrelic/newrelic/newrelic.jar"
  DB_HOST: "217.76.49.138"
  DB_DATABASE: "prueba_conection"
  DB_USER: "link"
  CUALQUIERCOSA: "xxx"
