apiVersion: v1
kind: Service
metadata:
  name: saludo
  labels:
    app: saludo
spec:
  type: LoadBalancer
  selector:
    app: saludo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080